#!/bin/bash

echo "🔍 Google OAuth Redirect URI Debug Tool"
echo ""

echo "Current Configuration:"
echo "======================"
echo "Server expects: http://localhost:5800/v1/auth/callback/google"
echo ""

echo "📋 To fix this issue:"
echo ""
echo "1. Go to Google Cloud Console:"
echo "   https://console.cloud.google.com/"
echo ""
echo "2. Navigate to:"
echo "   APIs & Services → Credentials"
echo ""
echo "3. Find your OAuth 2.0 Client ID and click EDIT"
echo ""
echo "4. In 'Authorized redirect URIs', add exactly:"
echo "   http://localhost:5800/v1/auth/callback/google"
echo ""
echo "5. Remove any other redirect URIs"
echo ""
echo "6. Click SAVE"
echo ""

echo "🧪 Common redirect URI issues:"
echo "• Make sure there's NO trailing slash"
echo "• Use http:// (not https://) for localhost"
echo "• Port must match exactly (5800)"
echo "• Path must match exactly (/v1/auth/callback/google)"
echo ""

echo "🔄 After updating Google Console:"
echo "1. Wait 2-3 minutes for changes to propagate"
echo "2. Try the OAuth flow again"
echo "3. Clear browser cache if needed"
echo ""

echo "📝 Alternative: Use Google's OAuth Playground for testing"
echo "   https://developers.google.com/oauthplayground"
echo ""