#!/bin/bash

echo "🧪 Complete Google OAuth Test"
echo "=========================="
echo ""

echo "✅ Current Status:"
echo "   • Web Server: http://localhost:5173/"
echo "   • API Server: http://localhost:5800/"
echo "   • Google Client ID: 351029698035-6kueu4as5bce178bimna3noa92ogc2tl.apps.googleusercontent.com"
echo ""

echo "🔗 Test Google OAuth Flow:"
echo "1. Open browser and go to: http://localhost:5173/"
echo "2. Click in the chat input area to trigger login modal"
echo "3. Click 'Sign in with Google' button"
echo "4. You should be redirected to Google's OAuth consent screen"
echo "5. Sign in with your Google account"
echo "6. Grant permissions for email and profile access"
echo "7. You'll be redirected back to: http://localhost:5800/v1/auth/callback/google"
echo "8. If successful, you'll see a success page with your profile"
echo "9. The window will close automatically and you'll be logged in"
echo ""

echo "🔍 If you get a 404 error:"
echo "   • The redirect URI in Google Cloud Console doesn't match"
echo "   • Go to: https://console.cloud.google.com/"
echo "   • Navigate to: APIs & Services → Credentials"
echo "   • Find your OAuth 2.0 Client ID and click EDIT"
echo "   • In 'Authorized redirect URIs', add exactly:"
echo "     http://localhost:5800/v1/auth/callback/google"
echo "   • Remove any other redirect URIs"
echo "   • Click SAVE"
echo "   • Wait 2-3 minutes for changes to propagate"
echo "   • Try the OAuth flow again"
echo ""

echo "🎯 Success Criteria:"
echo "   ✅ Login modal shows Google button"
echo "   ✅ Google button redirects to Google OAuth"
echo "   ✅ After authentication, redirected back to app"
echo "   ✅ Success page shows your Google profile"
echo "   ✅ Window closes automatically"
echo "   ✅ You're logged into the main application"
echo ""

echo "🚀 Ready to test! Visit http://localhost:5173/ now!"